-- 附檔以顯式 id 匯入假資料（GENERATED BY DEFAULT），
-- 需把各表 IDENTITY 起始值校正到 6，之後新增才不會撞主鍵。
ALTER TABLE invitation_record      ALTER COLUMN id RESTART WITH 6;
ALTER TABLE interview_arrangement  ALTER COLUMN id RESTART WITH 6;
ALTER TABLE mail_template          ALTER COLUMN id RESTART WITH 6;
ALTER TABLE mail_send_record       ALTER COLUMN id RESTART WITH 6;
ALTER TABLE manager_directory      ALTER COLUMN id RESTART WITH 6;
