-- =====================================================================
-- 招募系統 · H2 in-memory 初始化 SQL（DDL + 每表 5 筆假資料）
-- 依 API 規格 v2：invitationId 自動遞增；寄信不做佇列，改以
-- mail_send_record.invitation_id UNIQUE 作冪等鍵。
-- 假資料的職稱／管道／婉拒原因／範本鍵均參考「職缺 1.xlsx」。
-- =====================================================================

-- ---------- DDL ----------
DROP TABLE IF EXISTS mail_send_record;
DROP TABLE IF EXISTS mail_template;
DROP TABLE IF EXISTS manager_directory;
DROP TABLE IF EXISTS interview_arrangement;
DROP TABLE IF EXISTS invitation_record;

-- 邀約紀錄（主檔 · 單一真實來源）
CREATE TABLE invitation_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(50)  NOT NULL,
    email            VARCHAR(120) NOT NULL,
    phone            VARCHAR(20),
    resume_no        VARCHAR(30),             -- 有值=104來源；無值=其他管道
    resume_link      VARCHAR(255),            -- 新增求職者成功後系統自動帶入（假資料 /resume/{id}）
    channel          VARCHAR(40),             -- 招募管道
    job_title        VARCHAR(60),             -- 職稱
    inviter          VARCHAR(60),             -- 邀請人（發出邀約的 HR，英文名.英文姓氏；未做登入，先寫死）
    -- 性別／上機試題類型／面試地點：基本資料已移置 interview_arrangement（HR 手動填）
    contact_status   VARCHAR(30)  NOT NULL,   -- ContactStatus
    invite_sent_at   TIMESTAMP,               -- 一面邀請寄出（三個月防重複基準）
    second_invite_at TIMESTAMP,               -- 二邀日期
    decline_reason   VARCHAR(60),             -- 婉拒原因
    result           VARCHAR(30),             -- 最終結果 OFFER_EXTENDED/OFFER_ACCEPTED/THANKS_LETTER/DECLINED/BLACKLIST
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 面試安排（信件溝通中後單向帶入，一位一列）
CREATE TABLE interview_arrangement (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id           BIGINT NOT NULL UNIQUE,
    candidate_name          VARCHAR(50),           -- 系統帶入
    job_title               VARCHAR(60),           -- 系統帶入
    resume_link             VARCHAR(255),          -- 系統帶入（主管檢視）
    gender                  VARCHAR(10),           -- HR 手動填（下拉 MALE/FEMALE）；基本資料自邀約移置
    exam_type               VARCHAR(10),           -- HR 手動填（下拉 基本/AI）＝上機考題目
    location                VARCHAR(10),           -- HR 手動填（下拉 南港/板橋）
    interview_manager       VARCHAR(50),           -- 主管可寫：面試主管，可多人（Tom、John；生產以 / 或 & 分隔）
    selected_manager        VARCHAR(50),           -- HR 可寫：多主管時媒合後選定一位（寄信只 CC 此位）
    manager_preferred_dates VARCHAR(500),          -- 主管可寫：可面試日期，可多日期，支援換行（一主管一行）
    interview_time          TIMESTAMP,             -- HR 可寫：一面時間（排面試時間；不可帶入過去時間）
    manager_remark          VARCHAR(255),          -- 主管可寫：主管備註（優先給 Sherry 面試）
    interview_prep_sheet    VARCHAR(255),          -- 面試準備表連結
    basic_info_sheet        VARCHAR(255),          -- 基本資料表連結（{{面試前資料}} 後備）
    candidate_reply_link    VARCHAR(255),          -- 面試者回傳資料連結（雲端問卷填畢後系統自動回寫；供主管檢視）
    mail_system_status      VARCHAR(20),           -- 回傳 Mail System 狀態（例：已處理）
    mail_sent_at            TIMESTAMP,             -- 最近一次發信時間（成功或失敗皆記，供辨識是哪次寄的）
    manager_assigned_at     TIMESTAMP,             -- 系統：判 7 天反灰用
    calendar_id             VARCHAR(120),          -- 保留，本期不做
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_arr_inv FOREIGN KEY (invitation_id) REFERENCES invitation_record(id)
);

-- 面試主管通訊錄（名字 → 公司信箱；供寄信 CC 面試主管解析用）
CREATE TABLE manager_directory (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL,
    email VARCHAR(120) NOT NULL
);

-- 信件範本（選取鍵＝ exam_type × location × job_title）
CREATE TABLE mail_template (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_type  VARCHAR(10),        -- 基本 / AI / 無
    location   VARCHAR(10),        -- 南港 / 板橋
    job_title  VARCHAR(60),
    body       CLOB,
    CONSTRAINT uq_template UNIQUE (exam_type, location, job_title)
);

-- 寄信結果（＝原「設定與紀錄」）；invitation_id UNIQUE 即冪等鍵
CREATE TABLE mail_send_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id    BIGINT NOT NULL UNIQUE,   -- 一個邀約至多一筆（防重寄）
    email            VARCHAR(120),
    gender           VARCHAR(10),
    job_title        VARCHAR(60),
    exam_type        VARCHAR(10),
    location         VARCHAR(10),
    interview_time   TIMESTAMP,
    form_link        VARCHAR(255),
    cc_manager_email VARCHAR(512),             -- CC 面試主管（多位以逗號分隔）
    sent_at          TIMESTAMP,
    status           VARCHAR(20),              -- SUCCESS / FAILED
    error_message    VARCHAR(255),
    CONSTRAINT fk_send_inv FOREIGN KEY (invitation_id) REFERENCES invitation_record(id)
);

-- ---------- 假資料：invitation_record（5 筆，涵蓋各狀態）----------
INSERT INTO invitation_record
(id, name, email, phone, resume_no, resume_link, channel, job_title, inviter, contact_status, invite_sent_at, second_invite_at, decline_reason, result) VALUES
(1, '王小明', 'ming.wang@example.invalid',  '0912-345-678', 'R104-20260901', 'https://drive.example.invalid/resume/1', '104邀約',      'Java軟體工程師',       'amy.chung',   'EMAIL_CONTACT',        '2026-09-01 09:00:00', NULL,                  NULL, NULL),
(2, '李佳穎', 'jiaying.li@example.invalid', '0922-111-222', NULL,            'https://drive.example.invalid/resume/2', '緯育TibaME',   'C#.Net實習生',         'john.lee',    'SECOND_INVITE_PENDING','2026-09-01 09:30:00', '2026-09-02 10:00:00', NULL, NULL),
(3, '陳志豪', 'zhihao.chen@example.invalid','0933-333-444', 'R104-20260828', 'https://drive.example.invalid/resume/3', '104主動應徵',  '資深Java軟體工程師',   'amy.chung',   'COMMUNICATING',        '2026-08-28 10:00:00', NULL,                  NULL, NULL),
(4, '林品妤', 'pinyu.lin@example.invalid',  '0955-666-777', NULL,            'https://drive.example.invalid/resume/4', '員工推薦',     'SA系統分析師',         'grace.cheng', 'INTERVIEW_CONFIRMED',  '2026-08-25 14:00:00', NULL,                  NULL, NULL),
(5, '張書瑋', 'shuwei.chang@example.invalid','0966-888-999',NULL,            'https://drive.example.invalid/resume/5', 'CakeResume',   '軟體測試工程師',       'amy.chung',   'OFFER_EXTENDED',       '2026-08-10 11:00:00', NULL,                  NULL, NULL);

-- ---------- 假資料：interview_arrangement（5 筆）----------
INSERT INTO interview_arrangement
(id, invitation_id, candidate_name, job_title, resume_link, gender, exam_type, location, interview_manager, selected_manager, manager_preferred_dates, interview_time, manager_remark, interview_prep_sheet, basic_info_sheet, candidate_reply_link, mail_system_status, mail_sent_at, manager_assigned_at) VALUES
(1, 3, '陳志豪', '資深Java軟體工程師', 'https://drive.example.invalid/resume/3', NULL,     NULL,   NULL,   NULL,            NULL,     NULL,                   NULL,                  NULL, NULL,                                     NULL,                                     NULL,                                     NULL,     NULL,                  NULL),
(2, 4, '林品妤', 'SA系統分析師',       'https://drive.example.invalid/resume/4', 'FEMALE', 'AI',   '南港', 'Sherry/John',   'Sherry', 'Sherry 9/5 下午、9/8 上午' || CHAR(10) || 'John 9/10 下午、9/11 上午', '2026-09-08 10:00:00', '優先給 Sherry 面試', 'https://drive.example.invalid/prep/4',   'https://forms.example.invalid/basic/4',  NULL,                                     NULL,     NULL,                  '2026-08-26 09:00:00'),
(3, 5, '張書瑋', '軟體測試工程師',     'https://drive.example.invalid/resume/5', 'MALE',   '基本', '南港', 'Eric.J',        NULL,     '8/12 下午',           '2026-08-12 14:00:00', NULL,                 'https://drive.example.invalid/prep/5',   'https://forms.example.invalid/basic/5',  'https://forms.example.invalid/reply/5',  '已處理', '2026-08-11 16:05:00', '2026-08-11 09:00:00'),
(4, 1, '王小明', 'Java軟體工程師',     'https://drive.example.invalid/resume/1', NULL,     NULL,   NULL,   NULL,            NULL,     NULL,                   NULL,                  NULL,                 NULL,                                     NULL,                                     NULL,                                     NULL,     NULL,                  NULL),
(5, 2, '李佳穎', 'C#.Net實習生',       'https://drive.example.invalid/resume/2', NULL,     NULL,   NULL,   NULL,            NULL,     NULL,                   NULL,                  NULL,           NULL,                                     NULL,                                     NULL,                                     NULL,     NULL,                  NULL);

-- ---------- 假資料：manager_directory（面試主管信箱，5 筆；名字唯一；信箱皆加 test. 前綴供測試）----------
INSERT INTO manager_directory (id, name, email) VALUES
(1, 'Sherry', 'test.sherry.wang@hy-tech.com.tw'),
(2, 'Eric.J', 'test.eric.jiang@hy-tech.com.tw'),
(3, 'John',   'test.john.lee@hy-tech.com.tw'),
(4, 'Tom',    'test.tom.chen@hy-tech.com.tw'),
(5, 'Moritz', 'test.moritz.hsu@hy-tech.com.tw');

-- ---------- 假資料：mail_template（5 筆，參考信件範本鍵）----------
INSERT INTO mail_template (id, exam_type, location, job_title, body) VALUES
(1, '基本', '南港', 'Java軟體工程師',       '<p>親愛的 {{姓氏}}{{先生/小姐}} 您好，面試時間 {{面試時間}}（南港/基本上機考）。面試前資料：{{面試前資料}}</p>'),
(2, '基本', '板橋', 'Java軟體工程師',       '<p>親愛的 {{姓氏}}{{先生/小姐}} 您好，面試時間 {{面試時間}}（板橋/基本上機考）。面試前資料：{{面試前資料}}</p>'),
(3, 'AI',   '南港', 'C#.Net軟體工程師',     '<p>親愛的 {{姓氏}}{{先生/小姐}} 您好，面試時間 {{面試時間}}（南港/AI上機考）。面試前資料：{{面試前資料}}</p>'),
(4, '基本', '南港', '資深Java軟體工程師',   '<p>親愛的 {{姓氏}}{{先生/小姐}} 您好，面試時間 {{面試時間}}（南港/基本上機考）。面試前資料：{{面試前資料}}</p>'),
(5, 'AI',   '南港', 'SA系統分析師',         '<p>親愛的 {{姓氏}}{{先生/小姐}} 您好，面試時間 {{面試時間}}（南港/AI上機考）。面試前資料：{{面試前資料}}</p>');

-- ---------- 假資料：mail_send_record（5 筆；SUCCESS/FAILED 混合）----------
INSERT INTO mail_send_record
(id, invitation_id, email, gender, job_title, exam_type, location, interview_time, form_link, cc_manager_email, sent_at, status, error_message) VALUES
(1, 4, 'pinyu.lin@example.invalid',  'FEMALE', 'SA系統分析師',       'AI',   '南港', '2026-09-08 10:00:00', 'https://drive.example.invalid/form/4', 'test.sherry.wang@hy-tech.com.tw', '2026-09-02 15:20:00', 'SUCCESS', NULL),
(2, 5, 'shuwei.chang@example.invalid','MALE',  '軟體測試工程師',     '基本', '南港', '2026-08-12 14:00:00', 'https://drive.example.invalid/form/5', 'test.eric.jiang@hy-tech.com.tw', '2026-08-11 16:05:00', 'SUCCESS', NULL),
(3, 3, 'zhihao.chen@example.invalid','MALE',   '資深Java軟體工程師', '基本', '南港', NULL,                  NULL,                                   NULL,                     '2026-08-30 10:10:00', 'FAILED',  '查無信件範本（TEMPLATE_NOT_FOUND）'),
(4, 1, 'ming.wang@example.invalid',  'MALE',   'Java軟體工程師',     '基本', '南港', NULL,                  NULL,                                   NULL,                     '2026-09-03 09:40:00', 'FAILED',  '尚未確認面試，暫不寄送'),
(5, 2, 'jiaying.li@example.invalid', 'FEMALE', 'C#.Net實習生',       NULL,   NULL,   NULL,                  NULL,                                   NULL,                     '2026-09-01 10:00:00', 'FAILED',  'Email 退信，待更正重寄');
